export const MOVE_DURATION_FRAMES = 150
export const HIGHLIGHT_DURATION_FRAMES = 60
export const HIGHLIGHT_COLOR = 'blue'
export const LINE_WIDTH = 2
export const HIGHLIGHT_RADIUS = 15

export const ROOT_TARGET_X = 400
export const ROOT_TARGET_Y = 50
export const TARGET_X_GAP = 100
export const TARGET_Y_GAP = 100
export const RADIUS = 10
export const FILL_COLOR = 'red'
export const STROKE_COLOR = 'black'
export const ARROW_HEAD_ANGLE = Math.PI / 6
export const ARROW_HEAD_LENGTH = 10
export const ARROW_LINE_WIDTH = 2
export const FRAMES_BETWEEN_HIGHLIGHTS = 60
export const FRAMES_BEFORE_FIRST_HIGHLIGHT = 60
export const FRAMES_AFTER_LAST_HIGHLIGHT = 60
